apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-jenkins-pv
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  awsElasticBlockStore:
    volumeID: ""
    fsType: ext4

